#ifndef _ARM_VIDEO_UTILS_H_
#define _ARM_VIDEO_UTILS_H_

#define HAS_UVLC_ENCODE

#define HAS_UVLC_WRITE_BLOCK

#define HAS_VIDEO_WRITE_DATA

#define HAS_DO_QUANTIZE_INTRA_MB

#endif // _ARM_VIDEO_UTILS_H_
