#ifndef _VIDEO_PICTURE_DEFINES_H_
#define _VIDEO_PICTURE_DEFINES_H_

#define MCU_HEIGHT      8
#define MCU_WIDTH       8
#define MCU_BLOCK_SIZE  (MCU_HEIGHT * MCU_WIDTH)

// Offsets in video_picture_context structure
#define VIDEO_PICTURE_CONTEXT_Y_SRC      0
#define VIDEO_PICTURE_CONTEXT_CB_SRC     4
#define VIDEO_PICTURE_CONTEXT_CR_SRC     8
#define VIDEO_PICTURE_CONTEXT_Y_WOFFSET 12
#define VIDEO_PICTURE_CONTEXT_C_WOFFSET 16
#define VIDEO_PICTURE_CONTEXT_Y_HOFFSET 20

#endif // _VIDEO_PICTURE_DEFINES_H_
