// Autogenerated from source-files using the CreateNavdataFormat.py script

#ifdef NAVDATA_STRUCTS_INCLUDES
#include "ardrone_autonomy/navdata_demo.h"
#include "ardrone_autonomy/navdata_time.h"
#include "ardrone_autonomy/navdata_raw_measures.h"
#include "ardrone_autonomy/navdata_phys_measures.h"
#include "ardrone_autonomy/navdata_gyros_offsets.h"
#include "ardrone_autonomy/navdata_euler_angles.h"
#include "ardrone_autonomy/navdata_references.h"
#include "ardrone_autonomy/navdata_trims.h"
#include "ardrone_autonomy/navdata_rc_references.h"
#include "ardrone_autonomy/navdata_pwm.h"
#include "ardrone_autonomy/navdata_altitude.h"
#include "ardrone_autonomy/navdata_vision_raw.h"
#include "ardrone_autonomy/navdata_vision_of.h"
#include "ardrone_autonomy/navdata_vision.h"
#include "ardrone_autonomy/navdata_vision_perf.h"
#include "ardrone_autonomy/navdata_trackers_send.h"
#include "ardrone_autonomy/navdata_vision_detect.h"
#include "ardrone_autonomy/navdata_watchdog.h"
#include "ardrone_autonomy/navdata_adc_data_frame.h"
#include "ardrone_autonomy/navdata_video_stream.h"
#include "ardrone_autonomy/navdata_games.h"
#include "ardrone_autonomy/navdata_pressure_raw.h"
#include "ardrone_autonomy/navdata_magneto.h"
#include "ardrone_autonomy/navdata_wind_speed.h"
#include "ardrone_autonomy/navdata_kalman_pressure.h"
#include "ardrone_autonomy/navdata_hdvideo_stream.h"
#include "ardrone_autonomy/navdata_wifi.h"
#include "ardrone_autonomy/navdata_zimmu_3000.h"
#include <std_msgs/UInt16.h>
#include <std_msgs/UInt32.h>
#include <std_msgs/Float32.h>
#include <std_msgs/Int32.h>
#include <std_msgs/Int16.h>
#include <std_msgs/UInt8.h>
#include <ardrone_autonomy/vector31.h>
#include <ardrone_autonomy/vector21.h>
#include <ardrone_autonomy/matrix33.h>
#endif

#ifdef NAVDATA_STRUCTS_HEADER
	ros::Publisher pub_navdata_demo;
	bool enabled_navdata_demo;

	ros::Publisher pub_navdata_time;
	bool enabled_navdata_time;

	ros::Publisher pub_navdata_raw_measures;
	bool enabled_navdata_raw_measures;

	ros::Publisher pub_navdata_phys_measures;
	bool enabled_navdata_phys_measures;

	ros::Publisher pub_navdata_gyros_offsets;
	bool enabled_navdata_gyros_offsets;

	ros::Publisher pub_navdata_euler_angles;
	bool enabled_navdata_euler_angles;

	ros::Publisher pub_navdata_references;
	bool enabled_navdata_references;

	ros::Publisher pub_navdata_trims;
	bool enabled_navdata_trims;

	ros::Publisher pub_navdata_rc_references;
	bool enabled_navdata_rc_references;

	ros::Publisher pub_navdata_pwm;
	bool enabled_navdata_pwm;

	ros::Publisher pub_navdata_altitude;
	bool enabled_navdata_altitude;

	ros::Publisher pub_navdata_vision_raw;
	bool enabled_navdata_vision_raw;

	ros::Publisher pub_navdata_vision_of;
	bool enabled_navdata_vision_of;

	ros::Publisher pub_navdata_vision;
	bool enabled_navdata_vision;

	ros::Publisher pub_navdata_vision_perf;
	bool enabled_navdata_vision_perf;

	ros::Publisher pub_navdata_trackers_send;
	bool enabled_navdata_trackers_send;

	ros::Publisher pub_navdata_vision_detect;
	bool enabled_navdata_vision_detect;

	ros::Publisher pub_navdata_watchdog;
	bool enabled_navdata_watchdog;

	ros::Publisher pub_navdata_adc_data_frame;
	bool enabled_navdata_adc_data_frame;

	ros::Publisher pub_navdata_video_stream;
	bool enabled_navdata_video_stream;

	ros::Publisher pub_navdata_games;
	bool enabled_navdata_games;

	ros::Publisher pub_navdata_pressure_raw;
	bool enabled_navdata_pressure_raw;

	ros::Publisher pub_navdata_magneto;
	bool enabled_navdata_magneto;

	ros::Publisher pub_navdata_wind_speed;
	bool enabled_navdata_wind_speed;

	ros::Publisher pub_navdata_kalman_pressure;
	bool enabled_navdata_kalman_pressure;

	ros::Publisher pub_navdata_hdvideo_stream;
	bool enabled_navdata_hdvideo_stream;

	ros::Publisher pub_navdata_wifi;
	bool enabled_navdata_wifi;

	ros::Publisher pub_navdata_zimmu_3000;
	bool enabled_navdata_zimmu_3000;

	bool initialized_navdata_publishers;
	void PublishNavdataTypes(navdata_unpacked_t n);
#endif

#ifdef NAVDATA_STRUCTS_SOURCE
void ARDroneDriver::PublishNavdataTypes(navdata_unpacked_t n)
{
	if(!initialized_navdata_publishers)
	{
		initialized_navdata_publishers = true;

		enabled_navdata_demo = false;
		ros::param::get("~enable_navdata_demo", enabled_navdata_demo);

		if(enabled_navdata_demo)
		{
			pub_navdata_demo = node_handle.advertise<ardrone_autonomy::navdata_demo>("ardrone/navdata_demo", NAVDATA_QUEUE_SIZE);
		}

		enabled_navdata_time = false;
		ros::param::get("~enable_navdata_time", enabled_navdata_time);

		if(enabled_navdata_time)
		{
			pub_navdata_time = node_handle.advertise<ardrone_autonomy::navdata_time>("ardrone/navdata_time", NAVDATA_QUEUE_SIZE);
		}

		enabled_navdata_raw_measures = false;
		ros::param::get("~enable_navdata_raw_measures", enabled_navdata_raw_measures);

		if(enabled_navdata_raw_measures)
		{
			pub_navdata_raw_measures = node_handle.advertise<ardrone_autonomy::navdata_raw_measures>("ardrone/navdata_raw_measures", NAVDATA_QUEUE_SIZE);
		}

		enabled_navdata_phys_measures = false;
		ros::param::get("~enable_navdata_phys_measures", enabled_navdata_phys_measures);

		if(enabled_navdata_phys_measures)
		{
			pub_navdata_phys_measures = node_handle.advertise<ardrone_autonomy::navdata_phys_measures>("ardrone/navdata_phys_measures", NAVDATA_QUEUE_SIZE);
		}

		enabled_navdata_gyros_offsets = false;
		ros::param::get("~enable_navdata_gyros_offsets", enabled_navdata_gyros_offsets);

		if(enabled_navdata_gyros_offsets)
		{
			pub_navdata_gyros_offsets = node_handle.advertise<ardrone_autonomy::navdata_gyros_offsets>("ardrone/navdata_gyros_offsets", NAVDATA_QUEUE_SIZE);
		}

		enabled_navdata_euler_angles = false;
		ros::param::get("~enable_navdata_euler_angles", enabled_navdata_euler_angles);

		if(enabled_navdata_euler_angles)
		{
			pub_navdata_euler_angles = node_handle.advertise<ardrone_autonomy::navdata_euler_angles>("ardrone/navdata_euler_angles", NAVDATA_QUEUE_SIZE);
		}

		enabled_navdata_references = false;
		ros::param::get("~enable_navdata_references", enabled_navdata_references);

		if(enabled_navdata_references)
		{
			pub_navdata_references = node_handle.advertise<ardrone_autonomy::navdata_references>("ardrone/navdata_references", NAVDATA_QUEUE_SIZE);
		}

		enabled_navdata_trims = false;
		ros::param::get("~enable_navdata_trims", enabled_navdata_trims);

		if(enabled_navdata_trims)
		{
			pub_navdata_trims = node_handle.advertise<ardrone_autonomy::navdata_trims>("ardrone/navdata_trims", NAVDATA_QUEUE_SIZE);
		}

		enabled_navdata_rc_references = false;
		ros::param::get("~enable_navdata_rc_references", enabled_navdata_rc_references);

		if(enabled_navdata_rc_references)
		{
			pub_navdata_rc_references = node_handle.advertise<ardrone_autonomy::navdata_rc_references>("ardrone/navdata_rc_references", NAVDATA_QUEUE_SIZE);
		}

		enabled_navdata_pwm = false;
		ros::param::get("~enable_navdata_pwm", enabled_navdata_pwm);

		if(enabled_navdata_pwm)
		{
			pub_navdata_pwm = node_handle.advertise<ardrone_autonomy::navdata_pwm>("ardrone/navdata_pwm", NAVDATA_QUEUE_SIZE);
		}

		enabled_navdata_altitude = false;
		ros::param::get("~enable_navdata_altitude", enabled_navdata_altitude);

		if(enabled_navdata_altitude)
		{
			pub_navdata_altitude = node_handle.advertise<ardrone_autonomy::navdata_altitude>("ardrone/navdata_altitude", NAVDATA_QUEUE_SIZE);
		}

		enabled_navdata_vision_raw = false;
		ros::param::get("~enable_navdata_vision_raw", enabled_navdata_vision_raw);

		if(enabled_navdata_vision_raw)
		{
			pub_navdata_vision_raw = node_handle.advertise<ardrone_autonomy::navdata_vision_raw>("ardrone/navdata_vision_raw", NAVDATA_QUEUE_SIZE);
		}

		enabled_navdata_vision_of = false;
		ros::param::get("~enable_navdata_vision_of", enabled_navdata_vision_of);

		if(enabled_navdata_vision_of)
		{
			pub_navdata_vision_of = node_handle.advertise<ardrone_autonomy::navdata_vision_of>("ardrone/navdata_vision_of", NAVDATA_QUEUE_SIZE);
		}

		enabled_navdata_vision = false;
		ros::param::get("~enable_navdata_vision", enabled_navdata_vision);

		if(enabled_navdata_vision)
		{
			pub_navdata_vision = node_handle.advertise<ardrone_autonomy::navdata_vision>("ardrone/navdata_vision", NAVDATA_QUEUE_SIZE);
		}

		enabled_navdata_vision_perf = false;
		ros::param::get("~enable_navdata_vision_perf", enabled_navdata_vision_perf);

		if(enabled_navdata_vision_perf)
		{
			pub_navdata_vision_perf = node_handle.advertise<ardrone_autonomy::navdata_vision_perf>("ardrone/navdata_vision_perf", NAVDATA_QUEUE_SIZE);
		}

		enabled_navdata_trackers_send = false;
		ros::param::get("~enable_navdata_trackers_send", enabled_navdata_trackers_send);

		if(enabled_navdata_trackers_send)
		{
			pub_navdata_trackers_send = node_handle.advertise<ardrone_autonomy::navdata_trackers_send>("ardrone/navdata_trackers_send", NAVDATA_QUEUE_SIZE);
		}

		enabled_navdata_vision_detect = false;
		ros::param::get("~enable_navdata_vision_detect", enabled_navdata_vision_detect);

		if(enabled_navdata_vision_detect)
		{
			pub_navdata_vision_detect = node_handle.advertise<ardrone_autonomy::navdata_vision_detect>("ardrone/navdata_vision_detect", NAVDATA_QUEUE_SIZE);
		}

		enabled_navdata_watchdog = false;
		ros::param::get("~enable_navdata_watchdog", enabled_navdata_watchdog);

		if(enabled_navdata_watchdog)
		{
			pub_navdata_watchdog = node_handle.advertise<ardrone_autonomy::navdata_watchdog>("ardrone/navdata_watchdog", NAVDATA_QUEUE_SIZE);
		}

		enabled_navdata_adc_data_frame = false;
		ros::param::get("~enable_navdata_adc_data_frame", enabled_navdata_adc_data_frame);

		if(enabled_navdata_adc_data_frame)
		{
			pub_navdata_adc_data_frame = node_handle.advertise<ardrone_autonomy::navdata_adc_data_frame>("ardrone/navdata_adc_data_frame", NAVDATA_QUEUE_SIZE);
		}

		enabled_navdata_video_stream = false;
		ros::param::get("~enable_navdata_video_stream", enabled_navdata_video_stream);

		if(enabled_navdata_video_stream)
		{
			pub_navdata_video_stream = node_handle.advertise<ardrone_autonomy::navdata_video_stream>("ardrone/navdata_video_stream", NAVDATA_QUEUE_SIZE);
		}

		enabled_navdata_games = false;
		ros::param::get("~enable_navdata_games", enabled_navdata_games);

		if(enabled_navdata_games)
		{
			pub_navdata_games = node_handle.advertise<ardrone_autonomy::navdata_games>("ardrone/navdata_games", NAVDATA_QUEUE_SIZE);
		}

		enabled_navdata_pressure_raw = false;
		ros::param::get("~enable_navdata_pressure_raw", enabled_navdata_pressure_raw);

		if(enabled_navdata_pressure_raw)
		{
			pub_navdata_pressure_raw = node_handle.advertise<ardrone_autonomy::navdata_pressure_raw>("ardrone/navdata_pressure_raw", NAVDATA_QUEUE_SIZE);
		}

		enabled_navdata_magneto = false;
		ros::param::get("~enable_navdata_magneto", enabled_navdata_magneto);

		if(enabled_navdata_magneto)
		{
			pub_navdata_magneto = node_handle.advertise<ardrone_autonomy::navdata_magneto>("ardrone/navdata_magneto", NAVDATA_QUEUE_SIZE);
		}

		enabled_navdata_wind_speed = false;
		ros::param::get("~enable_navdata_wind_speed", enabled_navdata_wind_speed);

		if(enabled_navdata_wind_speed)
		{
			pub_navdata_wind_speed = node_handle.advertise<ardrone_autonomy::navdata_wind_speed>("ardrone/navdata_wind_speed", NAVDATA_QUEUE_SIZE);
		}

		enabled_navdata_kalman_pressure = false;
		ros::param::get("~enable_navdata_kalman_pressure", enabled_navdata_kalman_pressure);

		if(enabled_navdata_kalman_pressure)
		{
			pub_navdata_kalman_pressure = node_handle.advertise<ardrone_autonomy::navdata_kalman_pressure>("ardrone/navdata_kalman_pressure", NAVDATA_QUEUE_SIZE);
		}

		enabled_navdata_hdvideo_stream = false;
		ros::param::get("~enable_navdata_hdvideo_stream", enabled_navdata_hdvideo_stream);

		if(enabled_navdata_hdvideo_stream)
		{
			pub_navdata_hdvideo_stream = node_handle.advertise<ardrone_autonomy::navdata_hdvideo_stream>("ardrone/navdata_hdvideo_stream", NAVDATA_QUEUE_SIZE);
		}

		enabled_navdata_wifi = false;
		ros::param::get("~enable_navdata_wifi", enabled_navdata_wifi);

		if(enabled_navdata_wifi)
		{
			pub_navdata_wifi = node_handle.advertise<ardrone_autonomy::navdata_wifi>("ardrone/navdata_wifi", NAVDATA_QUEUE_SIZE);
		}

		enabled_navdata_zimmu_3000 = false;
		ros::param::get("~enable_navdata_zimmu_3000", enabled_navdata_zimmu_3000);

		if(enabled_navdata_zimmu_3000)
		{
			pub_navdata_zimmu_3000 = node_handle.advertise<ardrone_autonomy::navdata_zimmu_3000>("ardrone/navdata_zimmu_3000", NAVDATA_QUEUE_SIZE);
		}

	}

	if(enabled_navdata_demo && pub_navdata_demo.getNumSubscribers()>0)
	{
		ardrone_autonomy::navdata_demo msg;
		msg.drone_time = ((double)ardrone_time_to_usec(n.navdata_time.time))/1000000.0;

		{			
			uint16_t c = n.navdata_demo.tag;
			uint16_t m;
			m = c;

			msg.tag = m;
		}

		{			
			uint16_t c = n.navdata_demo.size;
			uint16_t m;
			m = c;

			msg.size = m;
		}

		{			
			uint32_t c = n.navdata_demo.ctrl_state;
			uint32_t m;
			m = c;

			msg.ctrl_state = m;
		}

		{			
			uint32_t c = n.navdata_demo.vbat_flying_percentage;
			uint32_t m;
			m = c;

			msg.vbat_flying_percentage = m;
		}

		{			
			float32_t c = n.navdata_demo.theta;
			float32_t m;
			m = c;

			msg.theta = m;
		}

		{			
			float32_t c = n.navdata_demo.phi;
			float32_t m;
			m = c;

			msg.phi = m;
		}

		{			
			float32_t c = n.navdata_demo.psi;
			float32_t m;
			m = c;

			msg.psi = m;
		}

		{			
			int32_t c = n.navdata_demo.altitude;
			int32_t m;
			m = c;

			msg.altitude = m;
		}

		{			
			float32_t c = n.navdata_demo.vx;
			float32_t m;
			m = c;

			msg.vx = m;
		}

		{			
			float32_t c = n.navdata_demo.vy;
			float32_t m;
			m = c;

			msg.vy = m;
		}

		{			
			float32_t c = n.navdata_demo.vz;
			float32_t m;
			m = c;

			msg.vz = m;
		}

		{			
			uint32_t c = n.navdata_demo.num_frames;
			uint32_t m;
			m = c;

			msg.num_frames = m;
		}

		{			
			uint32_t c = n.navdata_demo.detection_camera_type;
			uint32_t m;
			m = c;

			msg.detection_camera_type = m;
		}

		pub_navdata_demo.publish(msg);
	}

	if(enabled_navdata_time && pub_navdata_time.getNumSubscribers()>0)
	{
		ardrone_autonomy::navdata_time msg;
		msg.drone_time = ((double)ardrone_time_to_usec(n.navdata_time.time))/1000000.0;

		{			
			uint16_t c = n.navdata_time.tag;
			uint16_t m;
			m = c;

			msg.tag = m;
		}

		{			
			uint16_t c = n.navdata_time.size;
			uint16_t m;
			m = c;

			msg.size = m;
		}

		{			
			uint32_t c = n.navdata_time.time;
			uint32_t m;
			m = c;

			msg.time = m;
		}

		pub_navdata_time.publish(msg);
	}

	if(enabled_navdata_raw_measures && pub_navdata_raw_measures.getNumSubscribers()>0)
	{
		ardrone_autonomy::navdata_raw_measures msg;
		msg.drone_time = ((double)ardrone_time_to_usec(n.navdata_time.time))/1000000.0;

		{			
			uint16_t c = n.navdata_raw_measures.tag;
			uint16_t m;
			m = c;

			msg.tag = m;
		}

		{			
			uint16_t c = n.navdata_raw_measures.size;
			uint16_t m;
			m = c;

			msg.size = m;
		}

		for(int i=0; i<NB_GYROS; i++)
		{			
			int16_t c = n.navdata_raw_measures.raw_gyros[i];
			int16_t m;
			m = c;

			msg.raw_gyros.push_back(m);
		}
		
		for(int i=0; i<2; i++)
		{			
			int16_t c = n.navdata_raw_measures.raw_gyros_110[i];
			int16_t m;
			m = c;

			msg.raw_gyros_110.push_back(m);
		}
		
		{			
			uint32_t c = n.navdata_raw_measures.vbat_raw;
			uint32_t m;
			m = c;

			msg.vbat_raw = m;
		}

		{			
			uint16_t c = n.navdata_raw_measures.us_debut_echo;
			uint16_t m;
			m = c;

			msg.us_debut_echo = m;
		}

		{			
			uint16_t c = n.navdata_raw_measures.us_fin_echo;
			uint16_t m;
			m = c;

			msg.us_fin_echo = m;
		}

		{			
			uint16_t c = n.navdata_raw_measures.us_association_echo;
			uint16_t m;
			m = c;

			msg.us_association_echo = m;
		}

		{			
			uint16_t c = n.navdata_raw_measures.us_distance_echo;
			uint16_t m;
			m = c;

			msg.us_distance_echo = m;
		}

		{			
			uint16_t c = n.navdata_raw_measures.us_courbe_temps;
			uint16_t m;
			m = c;

			msg.us_courbe_temps = m;
		}

		{			
			uint16_t c = n.navdata_raw_measures.us_courbe_valeur;
			uint16_t m;
			m = c;

			msg.us_courbe_valeur = m;
		}

		{			
			uint16_t c = n.navdata_raw_measures.us_courbe_ref;
			uint16_t m;
			m = c;

			msg.us_courbe_ref = m;
		}

		{			
			uint16_t c = n.navdata_raw_measures.flag_echo_ini;
			uint16_t m;
			m = c;

			msg.flag_echo_ini = m;
		}

		{			
			uint16_t c = n.navdata_raw_measures.nb_echo;
			uint16_t m;
			m = c;

			msg.nb_echo = m;
		}

		{			
			uint32_t c = n.navdata_raw_measures.sum_echo;
			uint32_t m;
			m = c;

			msg.sum_echo = m;
		}

		{			
			int32_t c = n.navdata_raw_measures.alt_temp_raw;
			int32_t m;
			m = c;

			msg.alt_temp_raw = m;
		}

		{			
			int16_t c = n.navdata_raw_measures.gradient;
			int16_t m;
			m = c;

			msg.gradient = m;
		}

		pub_navdata_raw_measures.publish(msg);
	}

	if(enabled_navdata_phys_measures && pub_navdata_phys_measures.getNumSubscribers()>0)
	{
		ardrone_autonomy::navdata_phys_measures msg;
		msg.drone_time = ((double)ardrone_time_to_usec(n.navdata_time.time))/1000000.0;

		{			
			uint16_t c = n.navdata_phys_measures.tag;
			uint16_t m;
			m = c;

			msg.tag = m;
		}

		{			
			uint16_t c = n.navdata_phys_measures.size;
			uint16_t m;
			m = c;

			msg.size = m;
		}

		{			
			float32_t c = n.navdata_phys_measures.accs_temp;
			float32_t m;
			m = c;

			msg.accs_temp = m;
		}

		{			
			uint16_t c = n.navdata_phys_measures.gyro_temp;
			uint16_t m;
			m = c;

			msg.gyro_temp = m;
		}

		for(int i=0; i<NB_ACCS; i++)
		{			
			float32_t c = n.navdata_phys_measures.phys_accs[i];
			float32_t m;
			m = c;

			msg.phys_accs.push_back(m);
		}
		
		for(int i=0; i<NB_GYROS; i++)
		{			
			float32_t c = n.navdata_phys_measures.phys_gyros[i];
			float32_t m;
			m = c;

			msg.phys_gyros.push_back(m);
		}
		
		{			
			uint32_t c = n.navdata_phys_measures.alim3V3;
			uint32_t m;
			m = c;

			msg.alim3V3 = m;
		}

		{			
			uint32_t c = n.navdata_phys_measures.vrefEpson;
			uint32_t m;
			m = c;

			msg.vrefEpson = m;
		}

		{			
			uint32_t c = n.navdata_phys_measures.vrefIDG;
			uint32_t m;
			m = c;

			msg.vrefIDG = m;
		}

		pub_navdata_phys_measures.publish(msg);
	}

	if(enabled_navdata_gyros_offsets && pub_navdata_gyros_offsets.getNumSubscribers()>0)
	{
		ardrone_autonomy::navdata_gyros_offsets msg;
		msg.drone_time = ((double)ardrone_time_to_usec(n.navdata_time.time))/1000000.0;

		{			
			uint16_t c = n.navdata_gyros_offsets.tag;
			uint16_t m;
			m = c;

			msg.tag = m;
		}

		{			
			uint16_t c = n.navdata_gyros_offsets.size;
			uint16_t m;
			m = c;

			msg.size = m;
		}

		for(int i=0; i<NB_GYROS; i++)
		{			
			float32_t c = n.navdata_gyros_offsets.offset_g[i];
			float32_t m;
			m = c;

			msg.offset_g.push_back(m);
		}
		
		pub_navdata_gyros_offsets.publish(msg);
	}

	if(enabled_navdata_euler_angles && pub_navdata_euler_angles.getNumSubscribers()>0)
	{
		ardrone_autonomy::navdata_euler_angles msg;
		msg.drone_time = ((double)ardrone_time_to_usec(n.navdata_time.time))/1000000.0;

		{			
			uint16_t c = n.navdata_euler_angles.tag;
			uint16_t m;
			m = c;

			msg.tag = m;
		}

		{			
			uint16_t c = n.navdata_euler_angles.size;
			uint16_t m;
			m = c;

			msg.size = m;
		}

		{			
			float32_t c = n.navdata_euler_angles.theta_a;
			float32_t m;
			m = c;

			msg.theta_a = m;
		}

		{			
			float32_t c = n.navdata_euler_angles.phi_a;
			float32_t m;
			m = c;

			msg.phi_a = m;
		}

		pub_navdata_euler_angles.publish(msg);
	}

	if(enabled_navdata_references && pub_navdata_references.getNumSubscribers()>0)
	{
		ardrone_autonomy::navdata_references msg;
		msg.drone_time = ((double)ardrone_time_to_usec(n.navdata_time.time))/1000000.0;

		{			
			uint16_t c = n.navdata_references.tag;
			uint16_t m;
			m = c;

			msg.tag = m;
		}

		{			
			uint16_t c = n.navdata_references.size;
			uint16_t m;
			m = c;

			msg.size = m;
		}

		{			
			int32_t c = n.navdata_references.ref_theta;
			int32_t m;
			m = c;

			msg.ref_theta = m;
		}

		{			
			int32_t c = n.navdata_references.ref_phi;
			int32_t m;
			m = c;

			msg.ref_phi = m;
		}

		{			
			int32_t c = n.navdata_references.ref_theta_I;
			int32_t m;
			m = c;

			msg.ref_theta_I = m;
		}

		{			
			int32_t c = n.navdata_references.ref_phi_I;
			int32_t m;
			m = c;

			msg.ref_phi_I = m;
		}

		{			
			int32_t c = n.navdata_references.ref_pitch;
			int32_t m;
			m = c;

			msg.ref_pitch = m;
		}

		{			
			int32_t c = n.navdata_references.ref_roll;
			int32_t m;
			m = c;

			msg.ref_roll = m;
		}

		{			
			int32_t c = n.navdata_references.ref_yaw;
			int32_t m;
			m = c;

			msg.ref_yaw = m;
		}

		{			
			int32_t c = n.navdata_references.ref_psi;
			int32_t m;
			m = c;

			msg.ref_psi = m;
		}

		{			
			float32_t c = n.navdata_references.vx_ref;
			float32_t m;
			m = c;

			msg.vx_ref = m;
		}

		{			
			float32_t c = n.navdata_references.vy_ref;
			float32_t m;
			m = c;

			msg.vy_ref = m;
		}

		{			
			float32_t c = n.navdata_references.theta_mod;
			float32_t m;
			m = c;

			msg.theta_mod = m;
		}

		{			
			float32_t c = n.navdata_references.phi_mod;
			float32_t m;
			m = c;

			msg.phi_mod = m;
		}

		{			
			float32_t c = n.navdata_references.k_v_x;
			float32_t m;
			m = c;

			msg.k_v_x = m;
		}

		{			
			float32_t c = n.navdata_references.k_v_y;
			float32_t m;
			m = c;

			msg.k_v_y = m;
		}

		{			
			uint32_t c = n.navdata_references.k_mode;
			uint32_t m;
			m = c;

			msg.k_mode = m;
		}

		{			
			float32_t c = n.navdata_references.ui_time;
			float32_t m;
			m = c;

			msg.ui_time = m;
		}

		{			
			float32_t c = n.navdata_references.ui_theta;
			float32_t m;
			m = c;

			msg.ui_theta = m;
		}

		{			
			float32_t c = n.navdata_references.ui_phi;
			float32_t m;
			m = c;

			msg.ui_phi = m;
		}

		{			
			float32_t c = n.navdata_references.ui_psi;
			float32_t m;
			m = c;

			msg.ui_psi = m;
		}

		{			
			float32_t c = n.navdata_references.ui_psi_accuracy;
			float32_t m;
			m = c;

			msg.ui_psi_accuracy = m;
		}

		{			
			int32_t c = n.navdata_references.ui_seq;
			int32_t m;
			m = c;

			msg.ui_seq = m;
		}

		pub_navdata_references.publish(msg);
	}

	if(enabled_navdata_trims && pub_navdata_trims.getNumSubscribers()>0)
	{
		ardrone_autonomy::navdata_trims msg;
		msg.drone_time = ((double)ardrone_time_to_usec(n.navdata_time.time))/1000000.0;

		{			
			uint16_t c = n.navdata_trims.tag;
			uint16_t m;
			m = c;

			msg.tag = m;
		}

		{			
			uint16_t c = n.navdata_trims.size;
			uint16_t m;
			m = c;

			msg.size = m;
		}

		{			
			float32_t c = n.navdata_trims.angular_rates_trim_r;
			float32_t m;
			m = c;

			msg.angular_rates_trim_r = m;
		}

		{			
			float32_t c = n.navdata_trims.euler_angles_trim_theta;
			float32_t m;
			m = c;

			msg.euler_angles_trim_theta = m;
		}

		{			
			float32_t c = n.navdata_trims.euler_angles_trim_phi;
			float32_t m;
			m = c;

			msg.euler_angles_trim_phi = m;
		}

		pub_navdata_trims.publish(msg);
	}

	if(enabled_navdata_rc_references && pub_navdata_rc_references.getNumSubscribers()>0)
	{
		ardrone_autonomy::navdata_rc_references msg;
		msg.drone_time = ((double)ardrone_time_to_usec(n.navdata_time.time))/1000000.0;

		{			
			uint16_t c = n.navdata_rc_references.tag;
			uint16_t m;
			m = c;

			msg.tag = m;
		}

		{			
			uint16_t c = n.navdata_rc_references.size;
			uint16_t m;
			m = c;

			msg.size = m;
		}

		{			
			int32_t c = n.navdata_rc_references.rc_ref_pitch;
			int32_t m;
			m = c;

			msg.rc_ref_pitch = m;
		}

		{			
			int32_t c = n.navdata_rc_references.rc_ref_roll;
			int32_t m;
			m = c;

			msg.rc_ref_roll = m;
		}

		{			
			int32_t c = n.navdata_rc_references.rc_ref_yaw;
			int32_t m;
			m = c;

			msg.rc_ref_yaw = m;
		}

		{			
			int32_t c = n.navdata_rc_references.rc_ref_gaz;
			int32_t m;
			m = c;

			msg.rc_ref_gaz = m;
		}

		{			
			int32_t c = n.navdata_rc_references.rc_ref_ag;
			int32_t m;
			m = c;

			msg.rc_ref_ag = m;
		}

		pub_navdata_rc_references.publish(msg);
	}

	if(enabled_navdata_pwm && pub_navdata_pwm.getNumSubscribers()>0)
	{
		ardrone_autonomy::navdata_pwm msg;
		msg.drone_time = ((double)ardrone_time_to_usec(n.navdata_time.time))/1000000.0;

		{			
			uint16_t c = n.navdata_pwm.tag;
			uint16_t m;
			m = c;

			msg.tag = m;
		}

		{			
			uint16_t c = n.navdata_pwm.size;
			uint16_t m;
			m = c;

			msg.size = m;
		}

		{			
			uint8_t c = n.navdata_pwm.motor1;
			uint8_t m;
			m = c;

			msg.motor1 = m;
		}

		{			
			uint8_t c = n.navdata_pwm.motor2;
			uint8_t m;
			m = c;

			msg.motor2 = m;
		}

		{			
			uint8_t c = n.navdata_pwm.motor3;
			uint8_t m;
			m = c;

			msg.motor3 = m;
		}

		{			
			uint8_t c = n.navdata_pwm.motor4;
			uint8_t m;
			m = c;

			msg.motor4 = m;
		}

		{			
			uint8_t c = n.navdata_pwm.sat_motor1;
			uint8_t m;
			m = c;

			msg.sat_motor1 = m;
		}

		{			
			uint8_t c = n.navdata_pwm.sat_motor2;
			uint8_t m;
			m = c;

			msg.sat_motor2 = m;
		}

		{			
			uint8_t c = n.navdata_pwm.sat_motor3;
			uint8_t m;
			m = c;

			msg.sat_motor3 = m;
		}

		{			
			uint8_t c = n.navdata_pwm.sat_motor4;
			uint8_t m;
			m = c;

			msg.sat_motor4 = m;
		}

		{			
			float32_t c = n.navdata_pwm.gaz_feed_forward;
			float32_t m;
			m = c;

			msg.gaz_feed_forward = m;
		}

		{			
			float32_t c = n.navdata_pwm.gaz_altitude;
			float32_t m;
			m = c;

			msg.gaz_altitude = m;
		}

		{			
			float32_t c = n.navdata_pwm.altitude_integral;
			float32_t m;
			m = c;

			msg.altitude_integral = m;
		}

		{			
			float32_t c = n.navdata_pwm.vz_ref;
			float32_t m;
			m = c;

			msg.vz_ref = m;
		}

		{			
			int32_t c = n.navdata_pwm.u_pitch;
			int32_t m;
			m = c;

			msg.u_pitch = m;
		}

		{			
			int32_t c = n.navdata_pwm.u_roll;
			int32_t m;
			m = c;

			msg.u_roll = m;
		}

		{			
			int32_t c = n.navdata_pwm.u_yaw;
			int32_t m;
			m = c;

			msg.u_yaw = m;
		}

		{			
			float32_t c = n.navdata_pwm.yaw_u_I;
			float32_t m;
			m = c;

			msg.yaw_u_I = m;
		}

		{			
			int32_t c = n.navdata_pwm.u_pitch_planif;
			int32_t m;
			m = c;

			msg.u_pitch_planif = m;
		}

		{			
			int32_t c = n.navdata_pwm.u_roll_planif;
			int32_t m;
			m = c;

			msg.u_roll_planif = m;
		}

		{			
			int32_t c = n.navdata_pwm.u_yaw_planif;
			int32_t m;
			m = c;

			msg.u_yaw_planif = m;
		}

		{			
			float32_t c = n.navdata_pwm.u_gaz_planif;
			float32_t m;
			m = c;

			msg.u_gaz_planif = m;
		}

		{			
			uint16_t c = n.navdata_pwm.current_motor1;
			uint16_t m;
			m = c;

			msg.current_motor1 = m;
		}

		{			
			uint16_t c = n.navdata_pwm.current_motor2;
			uint16_t m;
			m = c;

			msg.current_motor2 = m;
		}

		{			
			uint16_t c = n.navdata_pwm.current_motor3;
			uint16_t m;
			m = c;

			msg.current_motor3 = m;
		}

		{			
			uint16_t c = n.navdata_pwm.current_motor4;
			uint16_t m;
			m = c;

			msg.current_motor4 = m;
		}

		{			
			float32_t c = n.navdata_pwm.altitude_der;
			float32_t m;
			m = c;

			msg.altitude_der = m;
		}

		pub_navdata_pwm.publish(msg);
	}

	if(enabled_navdata_altitude && pub_navdata_altitude.getNumSubscribers()>0)
	{
		ardrone_autonomy::navdata_altitude msg;
		msg.drone_time = ((double)ardrone_time_to_usec(n.navdata_time.time))/1000000.0;

		{			
			uint16_t c = n.navdata_altitude.tag;
			uint16_t m;
			m = c;

			msg.tag = m;
		}

		{			
			uint16_t c = n.navdata_altitude.size;
			uint16_t m;
			m = c;

			msg.size = m;
		}

		{			
			int32_t c = n.navdata_altitude.altitude_vision;
			int32_t m;
			m = c;

			msg.altitude_vision = m;
		}

		{			
			float32_t c = n.navdata_altitude.altitude_vz;
			float32_t m;
			m = c;

			msg.altitude_vz = m;
		}

		{			
			int32_t c = n.navdata_altitude.altitude_ref;
			int32_t m;
			m = c;

			msg.altitude_ref = m;
		}

		{			
			int32_t c = n.navdata_altitude.altitude_raw;
			int32_t m;
			m = c;

			msg.altitude_raw = m;
		}

		{			
			float32_t c = n.navdata_altitude.obs_accZ;
			float32_t m;
			m = c;

			msg.obs_accZ = m;
		}

		{			
			float32_t c = n.navdata_altitude.obs_alt;
			float32_t m;
			m = c;

			msg.obs_alt = m;
		}

		{			
			vector31_t c = n.navdata_altitude.obs_x;
			ardrone_autonomy::vector31 m;
			m.x = c.x;
			m.y = c.y;
			m.z = c.z;

			msg.obs_x = m;
		}

		{			
			uint32_t c = n.navdata_altitude.obs_state;
			uint32_t m;
			m = c;

			msg.obs_state = m;
		}

		{			
			vector21_t c = n.navdata_altitude.est_vb;
			ardrone_autonomy::vector21 m;
			m.x = c.x;
			m.y = c.y;

			msg.est_vb = m;
		}

		{			
			uint32_t c = n.navdata_altitude.est_state;
			uint32_t m;
			m = c;

			msg.est_state = m;
		}

		pub_navdata_altitude.publish(msg);
	}

	if(enabled_navdata_vision_raw && pub_navdata_vision_raw.getNumSubscribers()>0)
	{
		ardrone_autonomy::navdata_vision_raw msg;
		msg.drone_time = ((double)ardrone_time_to_usec(n.navdata_time.time))/1000000.0;

		{			
			uint16_t c = n.navdata_vision_raw.tag;
			uint16_t m;
			m = c;

			msg.tag = m;
		}

		{			
			uint16_t c = n.navdata_vision_raw.size;
			uint16_t m;
			m = c;

			msg.size = m;
		}

		{			
			float32_t c = n.navdata_vision_raw.vision_tx_raw;
			float32_t m;
			m = c;

			msg.vision_tx_raw = m;
		}

		{			
			float32_t c = n.navdata_vision_raw.vision_ty_raw;
			float32_t m;
			m = c;

			msg.vision_ty_raw = m;
		}

		{			
			float32_t c = n.navdata_vision_raw.vision_tz_raw;
			float32_t m;
			m = c;

			msg.vision_tz_raw = m;
		}

		pub_navdata_vision_raw.publish(msg);
	}

	if(enabled_navdata_vision_of && pub_navdata_vision_of.getNumSubscribers()>0)
	{
		ardrone_autonomy::navdata_vision_of msg;
		msg.drone_time = ((double)ardrone_time_to_usec(n.navdata_time.time))/1000000.0;

		{			
			uint16_t c = n.navdata_vision_of.tag;
			uint16_t m;
			m = c;

			msg.tag = m;
		}

		{			
			uint16_t c = n.navdata_vision_of.size;
			uint16_t m;
			m = c;

			msg.size = m;
		}

		for(int i=0; i<5; i++)
		{			
			float32_t c = n.navdata_vision_of.of_dx[i];
			float32_t m;
			m = c;

			msg.of_dx.push_back(m);
		}
		
		for(int i=0; i<5; i++)
		{			
			float32_t c = n.navdata_vision_of.of_dy[i];
			float32_t m;
			m = c;

			msg.of_dy.push_back(m);
		}
		
		pub_navdata_vision_of.publish(msg);
	}

	if(enabled_navdata_vision && pub_navdata_vision.getNumSubscribers()>0)
	{
		ardrone_autonomy::navdata_vision msg;
		msg.drone_time = ((double)ardrone_time_to_usec(n.navdata_time.time))/1000000.0;

		{			
			uint16_t c = n.navdata_vision.tag;
			uint16_t m;
			m = c;

			msg.tag = m;
		}

		{			
			uint16_t c = n.navdata_vision.size;
			uint16_t m;
			m = c;

			msg.size = m;
		}

		{			
			uint32_t c = n.navdata_vision.vision_state;
			uint32_t m;
			m = c;

			msg.vision_state = m;
		}

		{			
			int32_t c = n.navdata_vision.vision_misc;
			int32_t m;
			m = c;

			msg.vision_misc = m;
		}

		{			
			float32_t c = n.navdata_vision.vision_phi_trim;
			float32_t m;
			m = c;

			msg.vision_phi_trim = m;
		}

		{			
			float32_t c = n.navdata_vision.vision_phi_ref_prop;
			float32_t m;
			m = c;

			msg.vision_phi_ref_prop = m;
		}

		{			
			float32_t c = n.navdata_vision.vision_theta_trim;
			float32_t m;
			m = c;

			msg.vision_theta_trim = m;
		}

		{			
			float32_t c = n.navdata_vision.vision_theta_ref_prop;
			float32_t m;
			m = c;

			msg.vision_theta_ref_prop = m;
		}

		{			
			int32_t c = n.navdata_vision.new_raw_picture;
			int32_t m;
			m = c;

			msg.new_raw_picture = m;
		}

		{			
			float32_t c = n.navdata_vision.theta_capture;
			float32_t m;
			m = c;

			msg.theta_capture = m;
		}

		{			
			float32_t c = n.navdata_vision.phi_capture;
			float32_t m;
			m = c;

			msg.phi_capture = m;
		}

		{			
			float32_t c = n.navdata_vision.psi_capture;
			float32_t m;
			m = c;

			msg.psi_capture = m;
		}

		{			
			int32_t c = n.navdata_vision.altitude_capture;
			int32_t m;
			m = c;

			msg.altitude_capture = m;
		}

		{			
			uint32_t c = n.navdata_vision.time_capture;
			uint32_t m;
			m = c;

			msg.time_capture = m;
		}

		{			
			velocities_t c = n.navdata_vision.body_v;
			ardrone_autonomy::vector31 m;
			m.x = c.x;
			m.y = c.y;
			m.z = c.z;

			msg.body_v = m;
		}

		{			
			float32_t c = n.navdata_vision.delta_phi;
			float32_t m;
			m = c;

			msg.delta_phi = m;
		}

		{			
			float32_t c = n.navdata_vision.delta_theta;
			float32_t m;
			m = c;

			msg.delta_theta = m;
		}

		{			
			float32_t c = n.navdata_vision.delta_psi;
			float32_t m;
			m = c;

			msg.delta_psi = m;
		}

		{			
			uint32_t c = n.navdata_vision.gold_defined;
			uint32_t m;
			m = c;

			msg.gold_defined = m;
		}

		{			
			uint32_t c = n.navdata_vision.gold_reset;
			uint32_t m;
			m = c;

			msg.gold_reset = m;
		}

		{			
			float32_t c = n.navdata_vision.gold_x;
			float32_t m;
			m = c;

			msg.gold_x = m;
		}

		{			
			float32_t c = n.navdata_vision.gold_y;
			float32_t m;
			m = c;

			msg.gold_y = m;
		}

		pub_navdata_vision.publish(msg);
	}

	if(enabled_navdata_vision_perf && pub_navdata_vision_perf.getNumSubscribers()>0)
	{
		ardrone_autonomy::navdata_vision_perf msg;
		msg.drone_time = ((double)ardrone_time_to_usec(n.navdata_time.time))/1000000.0;

		{			
			uint16_t c = n.navdata_vision_perf.tag;
			uint16_t m;
			m = c;

			msg.tag = m;
		}

		{			
			uint16_t c = n.navdata_vision_perf.size;
			uint16_t m;
			m = c;

			msg.size = m;
		}

		{			
			float32_t c = n.navdata_vision_perf.time_corners;
			float32_t m;
			m = c;

			msg.time_corners = m;
		}

		{			
			float32_t c = n.navdata_vision_perf.time_compute;
			float32_t m;
			m = c;

			msg.time_compute = m;
		}

		{			
			float32_t c = n.navdata_vision_perf.time_tracking;
			float32_t m;
			m = c;

			msg.time_tracking = m;
		}

		{			
			float32_t c = n.navdata_vision_perf.time_trans;
			float32_t m;
			m = c;

			msg.time_trans = m;
		}

		{			
			float32_t c = n.navdata_vision_perf.time_update;
			float32_t m;
			m = c;

			msg.time_update = m;
		}

		for(int i=0; i<NAVDATA_MAX_CUSTOM_TIME_SAVE; i++)
		{			
			float32_t c = n.navdata_vision_perf.time_custom[i];
			float32_t m;
			m = c;

			msg.time_custom.push_back(m);
		}
		
		pub_navdata_vision_perf.publish(msg);
	}

	if(enabled_navdata_trackers_send && pub_navdata_trackers_send.getNumSubscribers()>0)
	{
		ardrone_autonomy::navdata_trackers_send msg;
		msg.drone_time = ((double)ardrone_time_to_usec(n.navdata_time.time))/1000000.0;

		{			
			uint16_t c = n.navdata_trackers_send.tag;
			uint16_t m;
			m = c;

			msg.tag = m;
		}

		{			
			uint16_t c = n.navdata_trackers_send.size;
			uint16_t m;
			m = c;

			msg.size = m;
		}

		for(int i=0; i<DEFAULT_NB_TRACKERS_WIDTH * DEFAULT_NB_TRACKERS_HEIGHT; i++)
		{			
			int32_t c = n.navdata_trackers_send.locked[i];
			int32_t m;
			m = c;

			msg.locked.push_back(m);
		}
		
		for(int i=0; i<DEFAULT_NB_TRACKERS_WIDTH * DEFAULT_NB_TRACKERS_HEIGHT; i++)
		{			
			screen_point_t c = n.navdata_trackers_send.point[i];
			ardrone_autonomy::vector21 m;
			m.x = c.x;
			m.y = c.y;

			msg.point.push_back(m);
		}
		
		pub_navdata_trackers_send.publish(msg);
	}

	if(enabled_navdata_vision_detect && pub_navdata_vision_detect.getNumSubscribers()>0)
	{
		ardrone_autonomy::navdata_vision_detect msg;
		msg.drone_time = ((double)ardrone_time_to_usec(n.navdata_time.time))/1000000.0;

		{			
			uint16_t c = n.navdata_vision_detect.tag;
			uint16_t m;
			m = c;

			msg.tag = m;
		}

		{			
			uint16_t c = n.navdata_vision_detect.size;
			uint16_t m;
			m = c;

			msg.size = m;
		}

		{			
			uint32_t c = n.navdata_vision_detect.nb_detected;
			uint32_t m;
			m = c;

			msg.nb_detected = m;
		}

		for(int i=0; i<NB_NAVDATA_DETECTION_RESULTS; i++)
		{			
			uint32_t c = n.navdata_vision_detect.type[i];
			uint32_t m;
			m = c;

			msg.type.push_back(m);
		}
		
		for(int i=0; i<NB_NAVDATA_DETECTION_RESULTS; i++)
		{			
			uint32_t c = n.navdata_vision_detect.xc[i];
			uint32_t m;
			m = c;

			msg.xc.push_back(m);
		}
		
		for(int i=0; i<NB_NAVDATA_DETECTION_RESULTS; i++)
		{			
			uint32_t c = n.navdata_vision_detect.yc[i];
			uint32_t m;
			m = c;

			msg.yc.push_back(m);
		}
		
		for(int i=0; i<NB_NAVDATA_DETECTION_RESULTS; i++)
		{			
			uint32_t c = n.navdata_vision_detect.width[i];
			uint32_t m;
			m = c;

			msg.width.push_back(m);
		}
		
		for(int i=0; i<NB_NAVDATA_DETECTION_RESULTS; i++)
		{			
			uint32_t c = n.navdata_vision_detect.height[i];
			uint32_t m;
			m = c;

			msg.height.push_back(m);
		}
		
		for(int i=0; i<NB_NAVDATA_DETECTION_RESULTS; i++)
		{			
			uint32_t c = n.navdata_vision_detect.dist[i];
			uint32_t m;
			m = c;

			msg.dist.push_back(m);
		}
		
		for(int i=0; i<NB_NAVDATA_DETECTION_RESULTS; i++)
		{			
			float32_t c = n.navdata_vision_detect.orientation_angle[i];
			float32_t m;
			m = c;

			msg.orientation_angle.push_back(m);
		}
		
		for(int i=0; i<NB_NAVDATA_DETECTION_RESULTS; i++)
		{			
			matrix33_t c = n.navdata_vision_detect.rotation[i];
			ardrone_autonomy::matrix33 m;
			m.m11 = c.m11;
			m.m12 = c.m12;
			m.m13 = c.m13;
			m.m21 = c.m21;
			m.m22 = c.m22;
			m.m23 = c.m23;
			m.m31 = c.m31;
			m.m32 = c.m32;
			m.m33 = c.m33;

			msg.rotation.push_back(m);
		}
		
		for(int i=0; i<NB_NAVDATA_DETECTION_RESULTS; i++)
		{			
			vector31_t c = n.navdata_vision_detect.translation[i];
			ardrone_autonomy::vector31 m;
			m.x = c.x;
			m.y = c.y;
			m.z = c.z;

			msg.translation.push_back(m);
		}
		
		for(int i=0; i<NB_NAVDATA_DETECTION_RESULTS; i++)
		{			
			uint32_t c = n.navdata_vision_detect.camera_source[i];
			uint32_t m;
			m = c;

			msg.camera_source.push_back(m);
		}
		
		pub_navdata_vision_detect.publish(msg);
	}

	if(enabled_navdata_watchdog && pub_navdata_watchdog.getNumSubscribers()>0)
	{
		ardrone_autonomy::navdata_watchdog msg;
		msg.drone_time = ((double)ardrone_time_to_usec(n.navdata_time.time))/1000000.0;

		{			
			uint16_t c = n.navdata_watchdog.tag;
			uint16_t m;
			m = c;

			msg.tag = m;
		}

		{			
			uint16_t c = n.navdata_watchdog.size;
			uint16_t m;
			m = c;

			msg.size = m;
		}

		pub_navdata_watchdog.publish(msg);
	}

	if(enabled_navdata_adc_data_frame && pub_navdata_adc_data_frame.getNumSubscribers()>0)
	{
		ardrone_autonomy::navdata_adc_data_frame msg;
		msg.drone_time = ((double)ardrone_time_to_usec(n.navdata_time.time))/1000000.0;

		{			
			uint16_t c = n.navdata_adc_data_frame.tag;
			uint16_t m;
			m = c;

			msg.tag = m;
		}

		{			
			uint16_t c = n.navdata_adc_data_frame.size;
			uint16_t m;
			m = c;

			msg.size = m;
		}

		{			
			uint32_t c = n.navdata_adc_data_frame.version;
			uint32_t m;
			m = c;

			msg.version = m;
		}

		for(int i=0; i<32; i++)
		{			
			uint8_t c = n.navdata_adc_data_frame.data_frame[i];
			uint8_t m;
			m = c;

			msg.data_frame.push_back(m);
		}
		
		pub_navdata_adc_data_frame.publish(msg);
	}

	if(enabled_navdata_video_stream && pub_navdata_video_stream.getNumSubscribers()>0)
	{
		ardrone_autonomy::navdata_video_stream msg;
		msg.drone_time = ((double)ardrone_time_to_usec(n.navdata_time.time))/1000000.0;

		{			
			uint16_t c = n.navdata_video_stream.tag;
			uint16_t m;
			m = c;

			msg.tag = m;
		}

		{			
			uint16_t c = n.navdata_video_stream.size;
			uint16_t m;
			m = c;

			msg.size = m;
		}

		{			
			uint8_t c = n.navdata_video_stream.quant;
			uint8_t m;
			m = c;

			msg.quant = m;
		}

		{			
			uint32_t c = n.navdata_video_stream.frame_size;
			uint32_t m;
			m = c;

			msg.frame_size = m;
		}

		{			
			uint32_t c = n.navdata_video_stream.frame_number;
			uint32_t m;
			m = c;

			msg.frame_number = m;
		}

		{			
			uint32_t c = n.navdata_video_stream.atcmd_ref_seq;
			uint32_t m;
			m = c;

			msg.atcmd_ref_seq = m;
		}

		{			
			uint32_t c = n.navdata_video_stream.atcmd_mean_ref_gap;
			uint32_t m;
			m = c;

			msg.atcmd_mean_ref_gap = m;
		}

		{			
			float32_t c = n.navdata_video_stream.atcmd_var_ref_gap;
			float32_t m;
			m = c;

			msg.atcmd_var_ref_gap = m;
		}

		{			
			uint32_t c = n.navdata_video_stream.atcmd_ref_quality;
			uint32_t m;
			m = c;

			msg.atcmd_ref_quality = m;
		}

		{			
			uint32_t c = n.navdata_video_stream.desired_bitrate;
			uint32_t m;
			m = c;

			msg.desired_bitrate = m;
		}

		{			
			int32_t c = n.navdata_video_stream.data2;
			int32_t m;
			m = c;

			msg.data2 = m;
		}

		{			
			int32_t c = n.navdata_video_stream.data3;
			int32_t m;
			m = c;

			msg.data3 = m;
		}

		{			
			int32_t c = n.navdata_video_stream.data4;
			int32_t m;
			m = c;

			msg.data4 = m;
		}

		{			
			int32_t c = n.navdata_video_stream.data5;
			int32_t m;
			m = c;

			msg.data5 = m;
		}

		{			
			uint32_t c = n.navdata_video_stream.fifo_queue_level;
			uint32_t m;
			m = c;

			msg.fifo_queue_level = m;
		}

		pub_navdata_video_stream.publish(msg);
	}

	if(enabled_navdata_games && pub_navdata_games.getNumSubscribers()>0)
	{
		ardrone_autonomy::navdata_games msg;
		msg.drone_time = ((double)ardrone_time_to_usec(n.navdata_time.time))/1000000.0;

		{			
			uint16_t c = n.navdata_games.tag;
			uint16_t m;
			m = c;

			msg.tag = m;
		}

		{			
			uint16_t c = n.navdata_games.size;
			uint16_t m;
			m = c;

			msg.size = m;
		}

		{			
			uint32_t c = n.navdata_games.double_tap_counter;
			uint32_t m;
			m = c;

			msg.double_tap_counter = m;
		}

		{			
			uint32_t c = n.navdata_games.finish_line_counter;
			uint32_t m;
			m = c;

			msg.finish_line_counter = m;
		}

		pub_navdata_games.publish(msg);
	}

	if(enabled_navdata_pressure_raw && pub_navdata_pressure_raw.getNumSubscribers()>0)
	{
		ardrone_autonomy::navdata_pressure_raw msg;
		msg.drone_time = ((double)ardrone_time_to_usec(n.navdata_time.time))/1000000.0;

		{			
			uint16_t c = n.navdata_pressure_raw.tag;
			uint16_t m;
			m = c;

			msg.tag = m;
		}

		{			
			uint16_t c = n.navdata_pressure_raw.size;
			uint16_t m;
			m = c;

			msg.size = m;
		}

		{			
			int32_t c = n.navdata_pressure_raw.up;
			int32_t m;
			m = c;

			msg.up = m;
		}

		{			
			int16_t c = n.navdata_pressure_raw.ut;
			int16_t m;
			m = c;

			msg.ut = m;
		}

		{			
			int32_t c = n.navdata_pressure_raw.Temperature_meas;
			int32_t m;
			m = c;

			msg.Temperature_meas = m;
		}

		{			
			int32_t c = n.navdata_pressure_raw.Pression_meas;
			int32_t m;
			m = c;

			msg.Pression_meas = m;
		}

		pub_navdata_pressure_raw.publish(msg);
	}

	if(enabled_navdata_magneto && pub_navdata_magneto.getNumSubscribers()>0)
	{
		ardrone_autonomy::navdata_magneto msg;
		msg.drone_time = ((double)ardrone_time_to_usec(n.navdata_time.time))/1000000.0;

		{			
			uint16_t c = n.navdata_magneto.tag;
			uint16_t m;
			m = c;

			msg.tag = m;
		}

		{			
			uint16_t c = n.navdata_magneto.size;
			uint16_t m;
			m = c;

			msg.size = m;
		}

		{			
			int16_t c = n.navdata_magneto.mx;
			int16_t m;
			m = c;

			msg.mx = m;
		}

		{			
			int16_t c = n.navdata_magneto.my;
			int16_t m;
			m = c;

			msg.my = m;
		}

		{			
			int16_t c = n.navdata_magneto.mz;
			int16_t m;
			m = c;

			msg.mz = m;
		}

		{			
			vector31_t c = n.navdata_magneto.magneto_raw;
			ardrone_autonomy::vector31 m;
			m.x = c.x;
			m.y = c.y;
			m.z = c.z;

			msg.magneto_raw = m;
		}

		{			
			vector31_t c = n.navdata_magneto.magneto_rectified;
			ardrone_autonomy::vector31 m;
			m.x = c.x;
			m.y = c.y;
			m.z = c.z;

			msg.magneto_rectified = m;
		}

		{			
			vector31_t c = n.navdata_magneto.magneto_offset;
			ardrone_autonomy::vector31 m;
			m.x = c.x;
			m.y = c.y;
			m.z = c.z;

			msg.magneto_offset = m;
		}

		{			
			float32_t c = n.navdata_magneto.heading_unwrapped;
			float32_t m;
			m = c;

			msg.heading_unwrapped = m;
		}

		{			
			float32_t c = n.navdata_magneto.heading_gyro_unwrapped;
			float32_t m;
			m = c;

			msg.heading_gyro_unwrapped = m;
		}

		{			
			float32_t c = n.navdata_magneto.heading_fusion_unwrapped;
			float32_t m;
			m = c;

			msg.heading_fusion_unwrapped = m;
		}

		{			
			char c = n.navdata_magneto.magneto_calibration_ok;
			char m;
			m = c;

			msg.magneto_calibration_ok = m;
		}

		{			
			uint32_t c = n.navdata_magneto.magneto_state;
			uint32_t m;
			m = c;

			msg.magneto_state = m;
		}

		{			
			float32_t c = n.navdata_magneto.magneto_radius;
			float32_t m;
			m = c;

			msg.magneto_radius = m;
		}

		{			
			float32_t c = n.navdata_magneto.error_mean;
			float32_t m;
			m = c;

			msg.error_mean = m;
		}

		{			
			float32_t c = n.navdata_magneto.error_var;
			float32_t m;
			m = c;

			msg.error_var = m;
		}

		pub_navdata_magneto.publish(msg);
	}

	if(enabled_navdata_wind_speed && pub_navdata_wind_speed.getNumSubscribers()>0)
	{
		ardrone_autonomy::navdata_wind_speed msg;
		msg.drone_time = ((double)ardrone_time_to_usec(n.navdata_time.time))/1000000.0;

		{			
			uint16_t c = n.navdata_wind_speed.tag;
			uint16_t m;
			m = c;

			msg.tag = m;
		}

		{			
			uint16_t c = n.navdata_wind_speed.size;
			uint16_t m;
			m = c;

			msg.size = m;
		}

		{			
			float32_t c = n.navdata_wind_speed.wind_speed;
			float32_t m;
			m = c;

			msg.wind_speed = m;
		}

		{			
			float32_t c = n.navdata_wind_speed.wind_angle;
			float32_t m;
			m = c;

			msg.wind_angle = m;
		}

		{			
			float32_t c = n.navdata_wind_speed.wind_compensation_theta;
			float32_t m;
			m = c;

			msg.wind_compensation_theta = m;
		}

		{			
			float32_t c = n.navdata_wind_speed.wind_compensation_phi;
			float32_t m;
			m = c;

			msg.wind_compensation_phi = m;
		}

		{			
			float32_t c = n.navdata_wind_speed.state_x1;
			float32_t m;
			m = c;

			msg.state_x1 = m;
		}

		{			
			float32_t c = n.navdata_wind_speed.state_x2;
			float32_t m;
			m = c;

			msg.state_x2 = m;
		}

		{			
			float32_t c = n.navdata_wind_speed.state_x3;
			float32_t m;
			m = c;

			msg.state_x3 = m;
		}

		{			
			float32_t c = n.navdata_wind_speed.state_x4;
			float32_t m;
			m = c;

			msg.state_x4 = m;
		}

		{			
			float32_t c = n.navdata_wind_speed.state_x5;
			float32_t m;
			m = c;

			msg.state_x5 = m;
		}

		{			
			float32_t c = n.navdata_wind_speed.state_x6;
			float32_t m;
			m = c;

			msg.state_x6 = m;
		}

		{			
			float32_t c = n.navdata_wind_speed.magneto_debug1;
			float32_t m;
			m = c;

			msg.magneto_debug1 = m;
		}

		{			
			float32_t c = n.navdata_wind_speed.magneto_debug2;
			float32_t m;
			m = c;

			msg.magneto_debug2 = m;
		}

		{			
			float32_t c = n.navdata_wind_speed.magneto_debug3;
			float32_t m;
			m = c;

			msg.magneto_debug3 = m;
		}

		pub_navdata_wind_speed.publish(msg);
	}

	if(enabled_navdata_kalman_pressure && pub_navdata_kalman_pressure.getNumSubscribers()>0)
	{
		ardrone_autonomy::navdata_kalman_pressure msg;
		msg.drone_time = ((double)ardrone_time_to_usec(n.navdata_time.time))/1000000.0;

		{			
			uint16_t c = n.navdata_kalman_pressure.tag;
			uint16_t m;
			m = c;

			msg.tag = m;
		}

		{			
			uint16_t c = n.navdata_kalman_pressure.size;
			uint16_t m;
			m = c;

			msg.size = m;
		}

		{			
			float32_t c = n.navdata_kalman_pressure.offset_pressure;
			float32_t m;
			m = c;

			msg.offset_pressure = m;
		}

		{			
			float32_t c = n.navdata_kalman_pressure.est_z;
			float32_t m;
			m = c;

			msg.est_z = m;
		}

		{			
			float32_t c = n.navdata_kalman_pressure.est_zdot;
			float32_t m;
			m = c;

			msg.est_zdot = m;
		}

		{			
			float32_t c = n.navdata_kalman_pressure.est_bias_PWM;
			float32_t m;
			m = c;

			msg.est_bias_PWM = m;
		}

		{			
			float32_t c = n.navdata_kalman_pressure.est_biais_pression;
			float32_t m;
			m = c;

			msg.est_biais_pression = m;
		}

		{			
			float32_t c = n.navdata_kalman_pressure.offset_US;
			float32_t m;
			m = c;

			msg.offset_US = m;
		}

		{			
			float32_t c = n.navdata_kalman_pressure.prediction_US;
			float32_t m;
			m = c;

			msg.prediction_US = m;
		}

		{			
			float32_t c = n.navdata_kalman_pressure.cov_alt;
			float32_t m;
			m = c;

			msg.cov_alt = m;
		}

		{			
			float32_t c = n.navdata_kalman_pressure.cov_PWM;
			float32_t m;
			m = c;

			msg.cov_PWM = m;
		}

		{			
			float32_t c = n.navdata_kalman_pressure.cov_vitesse;
			float32_t m;
			m = c;

			msg.cov_vitesse = m;
		}

		{			
			bool_t c = n.navdata_kalman_pressure.bool_effet_sol;
			bool_t m;
			m = c;

			msg.bool_effet_sol = m;
		}

		{			
			float32_t c = n.navdata_kalman_pressure.somme_inno;
			float32_t m;
			m = c;

			msg.somme_inno = m;
		}

		{			
			bool_t c = n.navdata_kalman_pressure.flag_rejet_US;
			bool_t m;
			m = c;

			msg.flag_rejet_US = m;
		}

		{			
			float32_t c = n.navdata_kalman_pressure.u_multisinus;
			float32_t m;
			m = c;

			msg.u_multisinus = m;
		}

		{			
			float32_t c = n.navdata_kalman_pressure.gaz_altitude;
			float32_t m;
			m = c;

			msg.gaz_altitude = m;
		}

		{			
			bool_t c = n.navdata_kalman_pressure.Flag_multisinus;
			bool_t m;
			m = c;

			msg.Flag_multisinus = m;
		}

		{			
			bool_t c = n.navdata_kalman_pressure.Flag_multisinus_debut;
			bool_t m;
			m = c;

			msg.Flag_multisinus_debut = m;
		}

		pub_navdata_kalman_pressure.publish(msg);
	}

	if(enabled_navdata_hdvideo_stream && pub_navdata_hdvideo_stream.getNumSubscribers()>0)
	{
		ardrone_autonomy::navdata_hdvideo_stream msg;
		msg.drone_time = ((double)ardrone_time_to_usec(n.navdata_time.time))/1000000.0;

		{			
			uint16_t c = n.navdata_hdvideo_stream.tag;
			uint16_t m;
			m = c;

			msg.tag = m;
		}

		{			
			uint16_t c = n.navdata_hdvideo_stream.size;
			uint16_t m;
			m = c;

			msg.size = m;
		}

		{			
			uint32_t c = n.navdata_hdvideo_stream.hdvideo_state;
			uint32_t m;
			m = c;

			msg.hdvideo_state = m;
		}

		{			
			uint32_t c = n.navdata_hdvideo_stream.storage_fifo_nb_packets;
			uint32_t m;
			m = c;

			msg.storage_fifo_nb_packets = m;
		}

		{			
			uint32_t c = n.navdata_hdvideo_stream.storage_fifo_size;
			uint32_t m;
			m = c;

			msg.storage_fifo_size = m;
		}

		{			
			uint32_t c = n.navdata_hdvideo_stream.usbkey_size;
			uint32_t m;
			m = c;

			msg.usbkey_size = m;
		}

		{			
			uint32_t c = n.navdata_hdvideo_stream.usbkey_freespace;
			uint32_t m;
			m = c;

			msg.usbkey_freespace = m;
		}

		{			
			uint32_t c = n.navdata_hdvideo_stream.frame_number;
			uint32_t m;
			m = c;

			msg.frame_number = m;
		}

		{			
			uint32_t c = n.navdata_hdvideo_stream.usbkey_remaining_time;
			uint32_t m;
			m = c;

			msg.usbkey_remaining_time = m;
		}

		pub_navdata_hdvideo_stream.publish(msg);
	}

	if(enabled_navdata_wifi && pub_navdata_wifi.getNumSubscribers()>0)
	{
		ardrone_autonomy::navdata_wifi msg;
		msg.drone_time = ((double)ardrone_time_to_usec(n.navdata_time.time))/1000000.0;

		{			
			uint16_t c = n.navdata_wifi.tag;
			uint16_t m;
			m = c;

			msg.tag = m;
		}

		{			
			uint16_t c = n.navdata_wifi.size;
			uint16_t m;
			m = c;

			msg.size = m;
		}

		{			
			uint32_t c = n.navdata_wifi.link_quality;
			uint32_t m;
			m = c;

			msg.link_quality = m;
		}

		pub_navdata_wifi.publish(msg);
	}

	if(enabled_navdata_zimmu_3000 && pub_navdata_zimmu_3000.getNumSubscribers()>0)
	{
		ardrone_autonomy::navdata_zimmu_3000 msg;
		msg.drone_time = ((double)ardrone_time_to_usec(n.navdata_time.time))/1000000.0;

		{			
			uint16_t c = n.navdata_zimmu_3000.tag;
			uint16_t m;
			m = c;

			msg.tag = m;
		}

		{			
			uint16_t c = n.navdata_zimmu_3000.size;
			uint16_t m;
			m = c;

			msg.size = m;
		}

		{			
			int32_t c = n.navdata_zimmu_3000.vzimmuLSB;
			int32_t m;
			m = c;

			msg.vzimmuLSB = m;
		}

		{			
			float32_t c = n.navdata_zimmu_3000.vzfind;
			float32_t m;
			m = c;

			msg.vzfind = m;
		}

		pub_navdata_zimmu_3000.publish(msg);
	}


}
#endif




